pub fn resources() -> Vec<serde_json::Value> {
    vec![
        serde_json::from_str(include_str!("../vendor/schemas/core/1/command.schema.json")).unwrap(),
        serde_json::from_str(include_str!("../vendor/schemas/core/1/common.schema.json")).unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.authenticate.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.authenticate.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.capabilities.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.capabilities.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.describe.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.describe.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.effects.abort_obligation.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.effects.abort_obligation.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.effects.get.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.effects.get.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.events.notify.notification.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.events.read.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.events.read.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.events.subscribe.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.events.subscribe.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.events.unsubscribe.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.events.unsubscribe.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.feature_dependencies.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.feature_dependencies.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.grant.get.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.grant.get.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.grant.issue.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.grant.issue.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.grant.revoke.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.grant.revoke.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.negotiate.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/core.negotiate.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core/1/error-data.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!("../vendor/schemas/core/1/query.schema.json")).unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core-test/1/core-test.authority.claim.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core-test/1/core-test.authority.claim.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core-test/1/core-test.subject.applied_count.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core-test/1/core-test.subject.applied_count.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core-test/1/core-test.subject.get.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core-test/1/core-test.subject.get.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core-test/1/core-test.subject.put.params.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/schemas/core-test/1/core-test.subject.put.result.schema.json"
        ))
        .unwrap(),
        serde_json::from_str(include_str!(
            "../vendor/conformance/schemas/launch-config.schema.json"
        ))
        .unwrap(),
    ]
}
