[package]
name = "pio-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "pio"
path = "src/main.rs"

[dependencies]
pio-core = { path = "../pio-core" }
pio-host = { path = "../pio-host" }
anyhow.workspace = true
serde_json.workspace = true
pio-protocol = { path = "../pio-protocol" }
pio-codex = { path = "../pio-codex" }
